/* 
BUILDING THE TABLES
*/


create table ACCOUNTS(
    ACCOUNT_ID INT NOT NULL AUTO_INCREMENT ,
    ACCOUNT_NAME VARCHAR(25) NOT NULL,
    ACCOUNT_PASS VARCHAR(200) NOT NULL,
    ACCOUNT_EMAIL VARCHAR(25) UNIQUE,
    
    PRIMARY KEY(ACCOUNT_ID)
);



CREATE TABLE EXPENSES(
    EXPENSES_ID INT NOT NULL AUTO_INCREMENT ,
    ACCOUNT_ID INT NOT NULL,     
    CATEGORY VARCHAR(256),
    EXPECTED_AMOUNT DECIMAL NOT NULL,
    AMOUNT DECIMAL,
    DATE_IN DATETIME DEFAULT CURRENT_TIMESTAMP, 

    PRIMARY KEY (EXPENSES_ID),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ACCOUNT_ID)
    
);
CREATE TABLE INCOME(
    INCOME_ID INT NOT NULL AUTO_INCREMENT ,
    ACCOUNT_ID INT NOT NULL, 
    CATEGORY VARCHAR(256),
    EXPECTED_AMOUNT DECIMAL NOT NULL,
    AMOUNT DECIMAL NOT NULL,
     DATE_IN DATETIME DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (INCOME_ID),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ACCOUNT_ID)
   
);
CREATE TABLE BALANCE(
    BALANCE_ID INT NOT NULL AUTO_INCREMENT ,
    REF_TO INT NOT NULL,    
    EXPENSES_ID INT  NULL,
    INCOME_ID INT NULL,
    TOTAL_INCOME DECIMAL ,
    TOTAL_EXPENSES DECIMAL ,
    TOTAL_AMOUNT DECIMAL ,
    DATE_IN DATETIME DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (BALANCE_ID),
    FOREIGN KEY (EXPENSES_ID) REFERENCES EXPENSES(EXPENSES_ID),
    FOREIGN KEY (INCOME_ID) REFERENCES INCOME(INCOME_ID)

   
);



DELIMITER $$
 CREATE TRIGGER income_AI
   AFTER INSERT ON INCOME
     FOR EACH ROW
       BEGIN
          DECLARE summont decimal(10,2);
          DECLARE expunt decimal(10,2);
           DECLARE TB_AMOUNT decimal(10,2);

            SELECT SUM(AMOUNT) INTO summont from INCOME;
            SELECT SUM(AMOUNT) INTO expunt from EXPENSES;
            set TB_AMOUNT := summont-expunt;

          INSERT INTO BALANCE(REF_TO,INCOME_ID,TOTAL_INCOME,TOTAL_EXPENSES,TOTAL_AMOUNT)
          VALUES (NEW.ACCOUNT_ID,NEW.INCOME_ID,summont, expunt,TB_AMOUNT);
END;
$$
DELIMITER ;

DELIMITER $$
 CREATE TRIGGER expenses_AI
   AFTER INSERT ON EXPENSES
     FOR EACH ROW
       BEGIN
          DECLARE summont decimal(10,2);
          DECLARE expunt decimal(10,2);
           DECLARE TB_AMOUNT decimal(10,2);

            SELECT SUM(AMOUNT) INTO summont from INCOME;
            SELECT SUM(AMOUNT) INTO expunt from EXPENSES;
            set TB_AMOUNT := summont-expunt;

          INSERT INTO BALANCE(REF_TO,EXPENSES_ID,TOTAL_INCOME,TOTAL_EXPENSES,TOTAL_AMOUNT)
          VALUES (NEW.ACCOUNT_ID,NEW.EXPENSES_ID,summont, expunt,TB_AMOUNT);
END;
$$
DELIMITER ;
